# Generated by Django 5.2.7 on 2025-11-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(unique=True, verbose_name="название продукта")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание продукта")),
                ("preview", models.URLField(blank=True, null=True, verbose_name="просмотр продукта")),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name="цена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Добавлен")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменён")),
                ("is_deleted", models.BooleanField(default=False, verbose_name='"на удаление"')),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "db_table": "product",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChainLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="email")),
                ("country", models.CharField(blank=True, max_length=150, null=True, verbose_name="страна")),
                ("city", models.CharField(blank=True, max_length=150, null=True, verbose_name="город")),
                ("street", models.CharField(blank=True, max_length=200, null=True, verbose_name="улица")),
                ("house_number", models.CharField(max_length=10, verbose_name="номер дома")),
                (
                    "where_my_money",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name="задолженность"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Добавлен")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменён")),
                ("is_deleted", models.BooleanField(default=False, verbose_name='"на удаление"')),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="levels",
                        to="retail_chain.chainlink",
                        verbose_name="уровень участника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участник",
                "db_table": "chain_link",
                "ordering": ["name"],
            },
        ),
    ]
