# Generated by Django 5.2.7 on 2025-11-16 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("retail_chain", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chainlink",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="представитель",
            ),
        ),
        migrations.AddField(
            model_name="chainlink",
            name="product",
            field=models.ManyToManyField(blank=True, to="retail_chain.product", verbose_name="продукт"),
        ),
        migrations.AddIndex(
            model_name="chainlink",
            index=models.Index(fields=["city"], name="chain_link_city_index"),
        ),
    ]
