# Generated by Django 5.2.7 on 2026-10-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0003_chain_link_supplier_and_product_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainlink',
            options={'ordering': ['name'], 'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
    ]
